spring.datasource.url=jdbc:postgresql://localhost:5432/wordcounter
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info,metrics,env,beans,loggers,mappings
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=Word Frequency Battle
info.app.description=Microservice for word frequency analysis
info.app.version=0.0.1-SNAPSHOT